name: Build API service docker image

on:
  pull_request:
  push:
    paths:
      - "packages/api/*"
    branches-ignore:
      - latest

defaults:
  run:
    working-directory: packages/api

jobs:
  build:
    name: Publish API server docker image
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      rabbitmq:
        image: rabbitmq:3.9-management
        env:
          RABBITMQ_DEFAULT_VHOST: "livepeer"
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@latest

      - name: yarn install
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker build & push
        env:
          DOCKER_TAGS: ${{ steps.tags.outputs.tags }}
          VERSION: ${{ steps.tags.outputs.version }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          DOCKER_BUILDKIT: 1
        run: |
          yarn run docker:build
          yarn run docker:push

      - name: notify livepeer-infra
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
