name: "cron: Active streams cleanup"

on:
  push:
    branches:
      - vg/chore/active-cleanup-improv
  schedule:
    - cron: "*/5 * * * *" # run every 5 minutes

jobs:
  cleanup:
    strategy:
      matrix:
        env:
          - name: "staging"
            hostname: "livepeer.monster"
            api-token: ${{ secrets.LP_STAGING_API_ADMIN_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Clean-up ${{ matrix.env.name }} active streams
        run: |
          output_file="./cleaned-up-streams-${{ matrix.env.name }}.json"

          curl --fail --request POST \
          --url 'https://${{ matrix.env.hostname }}/api/stream/job/active-cleanup' \
          --header 'Authorization: Bearer ${{ matrix.env.api-token }}' \
          -o $output_file

          cleaned_count=$(jq '.cleanedUp | length' $output_file)
          echo "Cleaned up $cleaned_count streams in ${{ matrix.env.name }}"

      - name: Upload cleaned up streams file
        uses: actions/upload-artifact@v4
        with:
          name: ./cleaned-up-streams-${{ matrix.env.name }}.json
          path: ./cleaned-up-streams-${{ matrix.env.name }}.json
          retention-days: 30
