name: "cron: Update API usage (billing)"

on:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update usage table
        run: |
          curl --request POST \
          --url 'https://livepeer.studio/api/usage/update' \
          --header 'Authorization: Bearer ${{ secrets.LP_API_ADMIN_TOKEN }}'
