name: "cron: Active streams cleanup"

on:
  schedule:
    - cron: "*/5 * * * *" # run every 5 minutes

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Clean-up staging active streams
        run: |
          curl --fail --request POST \
          --url 'https://livepeer.monster/api/stream/job/active-cleanup' \
          --header 'Authorization: Bearer ${{ secrets.LP_STAGING_API_ADMIN_TOKEN }}'
