name: Test project

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Run tests defined for the project
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      rabbitmq:
        image: rabbitmq:3.9-management
        env:
          RABBITMQ_DEFAULT_VHOST: "livepeer"
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn tests with coverage
        run: yarn run coverage
