name: Build web service docker image

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@v0

      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker build & push
        env:
          DOCKER_TAGS: ${{ steps.tags.outputs.tags }}
          VERSION: ${{ steps.tags.outputs.version }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          DOCKER_BUILDKIT: 1
        run: |
          cd packages/www
          yarn run docker:build
          yarn run docker:push

      - name: notify livepeer-infra
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
