on: push
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker build
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_BUILDKIT: 1
        run: |
          export DOCKER_TAG=$(echo $BRANCH | tr -cd '[:alnum:]_')
          cd packages/www
          yarn run docker:build
          yarn run docker:push

          # Livepeer internal build alerting
          curl -X POST https://holy-bread-207a.livepeer.workers.dev
