name: Build www docker image

on:
  pull_request:
  push:
    paths:
      - "packages/www/*"
      - "packages/admin/*"
      - "packages/design-system/*"
    branches-ignore:
      - latest

defaults:
  run:
    working-directory: packages/www

jobs:
  build:
    name: Publish web service docker image
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Tags
        id: tags
        uses: livepeer/action-gh-release-tags@latest

      - name: docker login
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker build & push
        env:
          DOCKER_TAGS: ${{ steps.tags.outputs.tags }}
          VERSION: ${{ steps.tags.outputs.version }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          DOCKER_BUILDKIT: 1
        run: |
          yarn run docker:build
          yarn run docker:push

      - name: notify livepeer-infra
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
